version: '3'

services:
  whisper:
    container_name: whisper
    ports:
        - '9000:9000'
    environment:
        - ASR_MODEL=medium
        - ASR_ENGINE=openai_whisper
        - ASR_MODEL_PATH=/data/whisper/model
        - MODEL_IDLE_TIMEOUT=300
        - SAMPLE_RATE=16000
    image:  onerahmet/openai-whisper-asr-webservice:latest
    #image:  onerahmet/openai-whisper-asr-webservice:latest-gpu
    volumes:
        - ./user-data/model:/data/whisper/model
    restart: always
