  guacnetwork_compose:
    driver: bridge

services:
  guacd:
    container_name: guacd_compose
    image: guacamole/guacd:1.6.0
    networks:
      - guacnetwork_compose
    restart: always
    volumes:
      - ./drive:/drive:rw
      - ./record:/record:rw

  postgres:
    container_name: postgres_guacamole_compose
    image: postgres:15.2-alpine
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - guacnetwork_compose
    volumes:
      - ./init:/docker-entrypoint-initdb.d:z
      - ./data:/var/lib/postgresql/data:Z

  guacamole:
    container_name: guacamole_compose
    image: guacamole/guacamole:1.6.0
    restart: always
    depends_on:
      - guacd
      - postgres
    group_add:
      - "1000"
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_DATABASE: ${POSTGRES_DB}
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      RECORDING_SEARCH_PATH: /record
    networks:
      - guacnetwork_compose
    volumes:
      - ./record:/record:rw
    ports:
      - "${GUACAMOLE_PORT}:8080"
