#version: '3' #deprecated versiones nuevas de docker compose
services:
  qemu:
    container_name: qemu
    image: cnsoluciones/docker-qemu-arm64:1.0.0
    privileged: true
    environment:
      # Variables de arranque
      BOOT: "https://deb.debian.org/debian/dists/bookworm/main/installer-arm64/current/images/netboot/mini.iso"
      
      # Configuración básica
      CPU_CORES: "2"            # Número de cores
      RAM_SIZE: "4G"            # Cantidad de RAM
      
      # Configuración de disco principal
      DISK_NAME: "disk"         # Nombre base para los archivos de disco
      DISK_SIZE: "50G"          # Tamaño máximo del disco
      DISK_FORMAT: "qcow2"      # Formato: raw, qcow2, vmdk, vdi, vpc, vhdx
      DISK_TYPE: "scsi"         # Tipo: ide, sata, nvme, usb, scsi, blk, auto
      DISK_ALLOC: "off"         # Asignación: off = dinámico, on = pre-asignado
      #DISK_IO: "native"         # Modo I/O: native, threads, io_uring
      #DISK_CACHE: "none"        # Cache: none, writeback (mejor rendimiento)
      #DISK_DISCARD: "unmap"     # TRIM/Discard: unmap, ignore
      #DISK_FLAGS: ""            # Opciones adicionales para qcow2
      
      # CPU (opcional)
      #CPU_PIN: ""              # Opcional: Pinear CPU a cores específicos (ej: "0,1,2")
      
      # Discos adicionales (opcional)
      #DISK2_SIZE: ""           # Tamaño del segundo disco (si se necesita)
      #DISK3_SIZE: ""           # Tamaño del tercer disco
      #DISK4_SIZE: ""           # Tamaño del cuarto disco
      
      # Dispositivos de bloque (opcional)
      #DEVICE: ""               # Dispositivo de bloque principal (ej: /dev/sda)
      #DEVICE2: ""              # Segundo dispositivo
      #DEVICE3: ""              # Tercer dispositivo
      #DEVICE4: ""              # Cuarto dispositivo
      
      # Configuración de red (opcional)
      #NET_DEVICE: ""           # Dispositivo de red a usar
      #NET_DRIVER: ""           # Driver de red
      #NET_MODEL: ""            # Modelo de tarjeta de red
      
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    ports:
      - 8006:8006
    stop_grace_period: 2m
    volumes:
      - ./storage:/storage
